app:
    jwt:
        secret: gadgetarium

server:
    error:
        include-stacktrace: always

spring:
    datasource:
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        open-in-view: false


    mail:
        host: smtp.gmail.com
        port: 587
        username: ntoygonbaev098@gmail.com
        password: rexu gvod yszc tnhg
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    sql:
      init:
          continue-on-error: true
          mode: always

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 22MB
            max-file-size: 100MB
            max-request-size: 100MB

cloud:
      aws:
          credentials:
              access-key: AKIA6GBMDSJX4ELD67G5
              secret-key: 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
          region:
              static: eu-north-1
          stack:
              auto: false

application:
      bucket:
          name: gadgetarium-java12
