app:
    jwt:
        secret: gadgetarium

server:
    error:
        include-stacktrace: always

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        open-in-view: false


    mail:
        host: smtp.gmail.com
        port: 587
        username: ntoygonbaev098@gmail.com
        password: rexu gvod yszc tnhg
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    sql:
      init:
          continue-on-error: true
          mode: always

