spring:
    config:
        import:
            - classpath:/configs/amazon-services-config.yml
            - classpath:/configs/email-config.yml
            - classpath:/configs/database-config.yml
            - classpath:/configs/flyway-config.yml
            - classpath:/configs/payment-config.yml

server:
    error:
        include-stacktrace: always

app:
    jwt:
        secret: gadget-java-12