cloud:
  aws:
    credentials:
      access-key: AKIA3KYNRCVIBB2TALRT
      secret-key: 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
    region:
      static: eu-central-1

application:
  bucket:
    name: gadgetarium-b12

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 22MB
      max-file-size: 100MB
      max-request-size: 100MB