spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
     init:
        continue-on-error: true
        mode: always

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: false
    open-in-view: false

    properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect