spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gadgetarium22@gmail.com
    password: gcom ilti iegg egxq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true