#Java Mail sender
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ntoygonbaev098@gmail.com
    password: rexu gvod yszc tnhg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true