#FlyWay
flyway:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  url: ${POSTGRES_DB}

spring:
  flyway:
    enabled: false
    locations: classpath:db.migration
    baseline-on-migrate: false