paypal:
  client-id: AT1FdRng9wFvEgFpKFdCuan5ij3wYIrHK8kxTUg0k0J86IqbpBLKLDVGFJv4xambr2IJuKZySWULielu
  client-secret: EMddaQFaydygHp4EykEB9u6yncT4wcAPNfhD8PgARkyVLKltvYECN_WAbsP5CGKjAEs-pVZflUZa1fNf
  base-url: https://developer.paypal.com/dashboard/applications/live
  
