paypal:
  client-id: AQHmZGc8JzgtRqsxaXCCTj2aDzj0PYx-K4KWdmSEsx7J0KdeNeYywakI8ZHCxpqAt-ejyz2xAc3nhi1r
  client-secret: ED_cm6pEe6916pcwZgxpe7ZalipRri7zJWqETo6Km4VgIwAJrmvYwLw_9d-ljFOlYuWoHNeMRU7aHEh-
  base-url: https://api.paypal.com
  
